apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplewebsite
spec:
  selector:
    matchLabels:
      app: simple-website
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-website
    spec:
      containers:
      - name: simplewebsite
        image: oyinkz/simplewebsite
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: simplewebsiteservice
spec:
  type: NodePort
  selector:
    app: simple-website
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
    nodePort: 30037
